[package]
name = "two_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.11"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "two_sum_bench"
harness = false